In [18]:
import csv
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import nltk

In [19]:
filein = pd.read_csv("Weka_Edited_Bokmal.csv")
filein.head()

,W=-,W=a,W=af,W=at,W=da,W=de,W=dem,W=den,W=der,W=det,...,W=vil,W=dette,W=din,W=et,W=lille,W=na,W=skulde,distribution_nora,distribution_helmer,character_name
0,1,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0.560910,0.439090,nora
1,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0.840796,0.159204,nora
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.799854,0.200146,nora
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0.610674,0.389326,helmer
4,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0.859418,0.140582,nora

In [27]:
nora_data = filein[ filein["character_name"] == "nora " ]
nora_data.head()

,W=-,W=a,W=af,W=at,W=da,W=de,W=dem,W=den,W=der,W=det,...,W=vil,W=dette,W=din,W=et,W=lille,W=na,W=skulde,distribution_nora,distribution_helmer,character_name
0,1,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0.560910,0.439090,nora
1,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0.840796,0.159204,nora
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.799854,0.200146,nora
4,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0.859418,0.140582,nora
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.869839,0.130161,nora

In [28]:
fig = nora_data[nora_data.character_name == 'nora'].plot(kind='scatter', x='line_num' y='distribution_nora', color='orange', label='Nora')

fig.set_xlabel('Nora Distribution')
fig.set_ylabel('Line Number')
fig.set_title('Noral Distribution vs Line Number')

fig=plt.gcf()
fig.set_size_inches(10, 7)
plt.show()

SyntaxError: invalid syntax (<ipython-input-28-577d39182122>, line 1)